export const FLEET_MEMBERSHIP_PLANS = [
  {
    id: "driver_pro",
    name: "Driver Pro",
    price: "$9.99",
    period: "/mo",
    range: "Owner operators and independent drivers",
    positioning: "AI Roadside Intelligence Membership",
    cta: "Start Driver Pro",
    href: "/mechanic/checkout?plan=driver_pro",
    accent: "from-cyan-300 to-blue-400",
    highlighted: false,
    features: [
      "AI dispatch priority",
      "Saved truck profile",
      "Emergency roadside mode",
      "AI roadside assistant",
      "Preferred providers",
      "Live dispatch tracking",
      "Breakdown history",
      "Route-aware roadside intelligence",
      "AI issue triage",
      "One-tap AI dispatch",
      "Dispatch ETA visibility",
      "Roadside event timeline",
      "Smart provider recommendations",
    ],
  },
  {
    id: "fleet_starter",
    name: "Fleet Starter",
    price: "$99.99",
    period: "/mo",
    range: "Small trucking companies under 50 trucks",
    positioning: "Fleet Roadside Coordination Platform",
    cta: "Start Fleet Starter",
    href: "/mechanic/checkout?plan=fleet_starter",
    accent: "from-blue-300 to-indigo-400",
    highlighted: false,
    features: [
      "Everything in Driver Pro",
      "Fleet dashboard",
      "Multi-driver management",
      "Centralized roadside monitoring",
      "Fleet breakdown history",
      "Fleet-wide dispatch tracking",
      "Company roadside analytics",
      "Provider preference management",
      "Team accounts",
      "Roadside activity feed",
      "Fleet incident management",
      "Centralized dispatch visibility",
    ],
  },
  {
    id: "fleet_professional",
    name: "Fleet Professional",
    price: "$299.99",
    period: "/mo",
    range: "Medium fleets with 60 to 200 trucks",
    positioning: "AI Fleet Roadside Operations Software",
    cta: "Start Fleet Professional",
    href: "/mechanic/checkout?plan=fleet_professional",
    accent: "from-sky-300 to-cyan-300",
    highlighted: true,
    features: [
      "Everything in Fleet Starter",
      "Advanced AI dispatch management",
      "Fleet downtime analytics",
      "Recurring issue detection",
      "Route intelligence",
      "Roadside SLA tracking",
      "Provider performance analytics",
      "Roadside heatmaps",
      "Operational reporting",
      "Dispatch escalation workflows",
      "Maintenance trend tracking",
      "Operational intelligence dashboards",
    ],
  },
  {
    id: "fleet_enterprise",
    name: "Fleet Enterprise",
    price: "$599.99",
    period: "/mo",
    range: "Large fleets over 250 trucks and national carriers",
    positioning: "Enterprise Roadside Operations Infrastructure",
    cta: "Start Fleet Enterprise",
    href: "/mechanic/checkout?plan=fleet_enterprise",
    accent: "from-emerald-300 to-cyan-300",
    highlighted: false,
    features: [
      "Everything in Fleet Professional",
      "Enterprise roadside command center",
      "Multi-location operations",
      "API integrations",
      "Custom dispatch workflows",
      "Enterprise analytics",
      "Custom AI routing logic",
      "Dedicated support",
      "Enterprise onboarding",
      "Internal dispatch integration",
      "White-label options",
      "AI fleet intelligence systems",
    ],
  },
] as const;

export type FleetMembershipPlanId = (typeof FLEET_MEMBERSHIP_PLANS)[number]["id"];
